#! /usr/bin/perl

use strict;
use warnings;

my $animated=0;
my $first=1; # first image
my $only_list=0;
my $print_index=0;
my $max_n=1000;
my $buscador="google";
my $argc=scalar @ARGV;
while ($argc) {
	last if $ARGV[0] !~ /^-([a|b|d|f|g|i|l|m|y])([0-9]*)$/;
	my $option=$1;
	my $number=$2;
	$animated=1            if ($option eq "a");
	$buscador="google"     if ($option eq "g");
	$buscador="yahoo"      if ($option eq "y");
	$buscador="bing"       if ($option eq "b");
	$buscador="duckduckgo" if ($option eq "d");
	$only_list=1           if ($option eq "l");
	$print_index=1         if ($option eq "i");
	if ($number ne "") {
		$max_n=$number     if ($option eq "m");
		$first=$number     if ($option eq "f"); # only used in bing and duckduckgo
	}
	$argc--;
	shift @ARGV;
}

if ($argc == 0) {
	print "Usage: iget [-a] [-b|-d|-g|-y] [-l] [-i] [-f#] [-m#] search terms ...\n";
	exit 1;
}

my @chars=("a".."z");
my $auxfile; # random string
$auxfile .= $chars[rand @chars] for 1..12;

my $terminos=join('+',@ARGV);

my $vqd=0;
# in duckduckgo we must obtain first a numeric code called vqd
if ($buscador eq "duckduckgo") {
	my $auxrequest=`wget -O - https://duckduckgo.com?q=$terminos`;
	$auxrequest =~ /vqd='(\d*)'/;
	$vqd=$1;
}

my $ua="\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36\"";
my $url="https://www.google.es/search?\\\&tbm=isch\\\&tbs=isz:lt,islt:vga\\\&q=$terminos";
my $animated_option="\\\&tbs=itp:animated";
my $cookies="";
my $initial_number=1000;
my $regex='"ou":"([^"]*?)"';
if ($buscador eq "yahoo") {
	$url="https://images.search.yahoo.com/search/images?\\\&q=$terminos";
	$animated_option="\\\&imgty=gif";
	$cookies="--header=\"Cookie: sB=vm=p\"";
	$initial_number=2000;
	$regex='"iurl":"([^"]*?)"';
}
if ($buscador eq "bing") {
	$ua="";
	$url="https://www.bing.com/images/search?q=$terminos\\\&first=$first";
	$animated_option="\\\&qft=+filterui:photo-animatedgif";
	$cookies="--header=\"Cookie: SRCHHPGUSR=ADLT=OFF; _SS=SID=0\"";
	$initial_number=3000+$first-1;
	$regex='thumb" target="_blank" href="([^";=]*?[^/])" h=';
}
if ($buscador eq "duckduckgo") {
	$first=$first-1;
	$url="https://duckduckgo.com/i.js?q=$terminos\\\&s=$first\\\&p=-2\\\&vqd=$vqd";
	# safesearch off: tried options k=-2 and kp=-2 but do not work
	$animated_option="\\\&f=type:photo-animatedgif";
	$initial_number=4000+$first;
	$regex='"image":"([^"]*?)"';
}

$url=$url . $animated_option if $animated;
system("wget $cookies -O $auxfile --user-agent=$ua $url");

open(my $fh, $auxfile)
  or die "Could not open file '$auxfile' $!";

my @total= ();
while (my $row = <$fh>) {
	my @lista = $row =~ /$regex/g;
	push(@total, @lista);
}
close($fh) or die "Could not close file '$auxfile' $!";

$terminos =~ s/ /_/g;     # substitute spaces for underscores
my $i = $initial_number;
my $count=1;
foreach $a (@total) {
	$a =~ s/\(/\\\(/g;    # escape parentheses
	$a =~ s/\)/\\\)/g;
	$a =~ s/\&/\\\&/g;    # escape ampersands
	my $out = $terminos . $i;
	$out = $out . ".gif" if $animated;
	print "$i: " if $print_index;
	print "$a\n";
	system("wget --tries=1 --timeout=4 -O $out $a") if !$only_list;
	last if ($count==$max_n);
	$count++;
	$i++;
}
system("rm $auxfile");
