#! /bin/bash

# This script only works with Chrome and Firefox
# Dependencies: xdotool

# Usage: imacro [number of images]

# 1. Open an image search engine (google, yahoo, bing or duckduckgo)
# 2. Do any search
# 3. Click any image to see the preview
# 4. Put the mouse pointer in the middle of the image preview (without clicking)
# 5. Execute this script from a terminal
# 6. Enjoy

nmax=50
if [ $# -ge 1 ]; then nmax=$1; fi

window_chrome=`xwininfo -tree -root |grep " - Google Chrome" |head -n1`
window_firefox=`xwininfo -tree -root |grep " - Mozilla Firefox" |head -n1`

browser="none"
if [ "$window_chrome" != "" ]; then
	browser="Chrome"
	window_title=$window_chrome
fi
if [ "$window_firefox" != "" ]; then
	browser="Firefox"
	window_title=$window_firefox
fi
if [ $browser == "none" ]; then exit 1; fi


engine="none"
if [[ $window_title =~ " Google " ]]; then
	down_chrome=7
	down_firefox=11
	engine="Google" 
fi
if [[ $window_title =~ " Yahoo " ]]; then 
	down_chrome=2
	down_firefox=4
	engine="Yahoo"
fi
if [[ $window_title =~ " Bing " ]]; then 
	down_chrome=2
	down_firefox=4
	engine="Bing"
fi
if [[ $window_title =~ " DuckDuckGo " ]]; then 
	down_chrome=4
	down_firefox=11
	engine="DuckDuckGo"
fi
if [ $engine == "none" ]; then exit 1; fi


# Copy the word "Down" several times, depending on the browser and the search engine 
case "$browser" in
	"Chrome")  d="$down_chrome";;
	"Firefox") d="$down_firefox";;
esac
down=""
for i in `seq $d`
do
	down="$down Down"
done

# bring the window to foreground
xdotool search " $engine " windowactivate 2> /dev/null

for i in `seq $nmax`; do 
	sleep 1
	xdotool click 3
	sleep .5
	xdotool key $down Return
	xdotool search --sync "Save " &> /dev/null
	sleep .5
	xdotool key Return
	sleep 1
	xdotool key Right
done


