#! /usr/bin/perl

use strict;
use warnings;
my $animated=0;
if ($ARGV[0] eq "-a") {
	$animated=1;
	shift @ARGV;
}
my $terminos=join('+',@ARGV);
my $auxfile = "boryget.html";

my $url="https://images.search.yahoo.com/search/images?\\\&q=$terminos";
if ($animated) {
	$url=$url . "\\\&imgty=gif";
}
#if ($animated) {
#	my $url="https://www.google.es/search?\\\&tbm=isch\\\&tbs=isz:lt,islt:vga\\\&tbs=itp:animated\\\&q=$terminos";
#}
#else {
#	my $url="https://www.google.es/search?\\\&tbm=isch\\\&tbs=isz:lt,islt:vga\\\&q=$terminos";
#}
my $ua = "--user-agent=\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36\""; 
my $home=$ENV{"HOME"};
system("wget --load-cookie=$home/cookies-yahoo.txt $url -O $auxfile $ua\n");
open(my $fh, $auxfile)
  or die "Could not open file '$auxfile' $!";

my @total= ();
while (my $row = <$fh>) {
#   my @lista = $row =~ /imgurl=([^&]*)&/g;
    my @lista = $row =~ /"iurl":"([^"]*?)"/g;
	push(@total, @lista);
}
my $i = 2000;
foreach $a (@total) {
	$a =~ s/\(/\\\(/g;
	$a =~ s/\)/\\\)/g;
	my $out = $terminos . $i;
	if ($animated) { $out = $out . ".gif"; }
	system("wget --tries=1 --timeout=4 $a -O $out\n");
	$i++;
}
system("rm $auxfile");
